// =====================================================
// GRADE BASE — extracted from PROGRAMAÇÃO CANAL EDUCAÇÃO MARÇO 2026
// Keys use occurrence suffixes: [2ª], [3ª] for repeated programs
// =====================================================
/**
 * GRADE_BASE_EDUCACAO — Horários de referência por dia da semana extraídos
 * da planilha de programação do CANAL EDUCAÇÃO.
 * Estrutura: { gradeByDay: { "0": {...}, "1": {...}, ..., "6": {...} },
 *              gradeOrderByDay: { "0": [...], ... } }
 * Chave numérica em string: "0"=Dom, "1"=Seg, ..., "6"=Sáb.
 * Programas com múltiplas exibições usam sufixos: "VIDA DE MERENDEIRA [2ª]", "[3ª]" etc.
 *
 * [MOD canal-gov] Renomeado de `GRADE_BASE` para `GRADE_BASE_EDUCACAO` para
 * deixar explícito que esta é a grade do Canal Educação. Um alias
 * `GRADE_BASE` é mantido no fim do arquivo por compatibilidade com código
 * legado que ainda referencie o nome antigo.
 *
 * NOTA DE MIGRAÇÃO: esta grade contém alguns títulos de slot que citam o
 * Canal Gov (ex.: "GINT SERIADOS CANAL GOV", "DOCUMENTARIOS TV SENADO GOV"
 * — horários fixos reservados para conteúdo do Gov dentro da grade linear
 * da Educação). Optei por NÃO removê-los automaticamente nesta entrega,
 * porque não dá para saber com segurança, só pelos dados, se eles marcam
 * apenas uma reserva de horário (informação legítima da grade da
 * Educação, para não sobrepor programa nesse intervalo) ou se são de fato
 * conteúdo pertencente ao Gov que vazou para cá. Recomendo confirmar com
 * a área de programação antes de excluir essas entradas — ver
 * README-INTEGRACAO.md, seção "Pontos que precisam de decisão humana".
 */
const GRADE_BASE_EDUCACAO = {
  "gradeByDay": {
    "1": {
      "ESTAÇÕES": "06:00:00",
      "SEMENTES DA EDUCAÇÃO": "06:30:00",
      "PALALOOS": "07:00:00",
      "PLANETA PALAVRA": "07:10:00",
      "SONHOS E SAPATILHAS": "07:30:00",
      "SOL EM DÓ RÉ MI": "07:45:00",
      "IGARAPÉ MÁGICO": "08:00:00",
      "PASSADO DA HORA": "08:15:00",
      "ME LIGA NA LATA": "08:30:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA": "09:00:00",
      "SE LIGA NA EDUCAÇÃO": "09:30:00",
      "TRILHA DE LETRAS": "10:45:00",
      "HEROÍNAS NEGRAS BRASILEIRAS": "11:15:00",
      "GINT SERIADOS CANAL GOV": "11:25:00",
      "CONTA A VIRADA": "11:30:00",
      "MUTATIS MUTANDIS": "12:00:00",
      "SEMENTES DA EDUCAÇÃO [2ª]": "12:30:00",
      "SEM DÚVIDA NENHUMA": "13:00:00",
      "DOC 100 + NOVOS INSTITUTOS FEDERAIS": "13:15:00",
      "PALALOOS [2ª]": "13:30:00",
      "PLANETA PALAVRA [2ª]": "13:40:00",
      "SONHOS E SAPATILHAS [2ª]": "13:50:00",
      "SOL EM DÓ RÉ MI [2ª]": "14:05:00",
      "IGARAPÉ MÁGICO [2ª]": "14:15:00",
      "PASSADO DA HORA [2ª]": "14:30:00",
      "ME LIGA NA LATA [2ª]": "14:45:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]": "15:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]": "15:45:00",
      "GINT SERIADOS CANAL GOV [2ª]": "15:55:00",
      "SE LIGA NA EDUCAÇÃO [2ª]": "16:00:00",
      "TRILHA DE LETRAS [2ª]": "17:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]": "17:45:00",
      "GINT SERIADOS CANAL GOV [3ª]": "17:55:00",
      "CONTA A VIRADA [2ª]": "18:00:00",
      "MUTATIS MUTANDIS [2ª]": "18:30:00",
      "CAMINHOS DA REPORTAGEM": "19:00:00",
      "ADOLESCENTES E O MUNDO DIGITAL": "19:30:00",
      "SEMENTES DA EDUCAÇÃO [3ª]": "20:00:00",
      "SEM DÚVIDA NENHUMA [2ª]": "20:30:00",
      "DOC 100 + NOVOS INSTITUTOS FEDERAIS [2ª]": "20:45:00",
      "PARQUES DO BRASIL": "21:00:00",
      "MEU PEDAÇO DE BRASIL": "21:30:00",
      "TEÓPHILO OTTONI": "22:00:00",
      "ENTRE LONGES": "22:30:00",
      "SEMENTES DA EDUCAÇÃO [4ª]": "23:00:00",
      "ADOLESCENTES E O MUNDO DIGITAL [2ª]": "23:30:00"
    },
    "2": {
      "ADOLESCENTES E O MUNDO DIGITAL": "06:00:00",
      "SEMENTES DA EDUCAÇÃO": "06:30:00",
      "PALALOOS": "07:00:00",
      "PLANETA PALAVRA": "07:10:00",
      "SONHOS E SAPATILHAS": "07:30:00",
      "SOL EM DÓ RÉ MI": "07:45:00",
      "IGARAPÉ MÁGICO": "08:00:00",
      "PASSADO DA HORA": "08:15:00",
      "ME LIGA NA LATA": "08:30:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA": "09:00:00",
      "SE LIGA NA EDUCAÇÃO": "09:30:00",
      "ENTRELINHAS": "10:45:00",
      "HEROÍNAS NEGRAS BRASILEIRAS": "11:15:00",
      "GINT SERIADOS CANAL GOV": "11:25:00",
      "OLHA ELAS!": "11:30:00",
      "SEMENTES DA EDUCAÇÃO [2ª]": "12:30:00",
      "ADOLESCENTES E O MUNDO DIGITAL [2ª]": "13:00:00",
      "PALALOOS [2ª]": "13:30:00",
      "PLANETA PALAVRA [2ª]": "13:40:00",
      "SONHOS E SAPATILHAS [2ª]": "13:50:00",
      "SOL EM DÓ RÉ MI [2ª]": "14:05:00",
      "IGARAPÉ MÁGICO [2ª]": "14:15:00",
      "PASSADO DA HORA [2ª]": "14:30:00",
      "ME LIGA NA LATA [2ª]": "14:45:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]": "15:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]": "15:45:00",
      "GINT SERIADOS CANAL GOV [2ª]": "15:55:00",
      "SE LIGA NA EDUCAÇÃO [2ª]": "16:00:00",
      "ENTRELINHAS [2ª]": "17:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]": "17:45:00",
      "GINT SERIADOS CANAL GOV [3ª]": "17:55:00",
      "OLHA ELAS! [2ª]": "18:00:00",
      "CAMINHOS DA REPORTAGEM": "19:00:00",
      "INCLUSÃO PRA VALER": "19:30:00",
      "SEMENTES DA EDUCAÇÃO [3ª]": "20:00:00",
      "ADOLESCENTES E O MUNDO DIGITAL [3ª]": "20:30:00",
      "FORTES DO BRASIL": "21:00:00",
      "PARQUES DO BRASIL": "21:30:00",
      "SAL A GOSTO": "22:00:00",
      "TEÓPHILO OTTONI": "22:30:00",
      "SEMENTES DA EDUCAÇÃO [4ª]": "23:00:00",
      "INCLUSÃO PRA VALER [2ª]": "23:30:00"
    },
    "3": {
      "INCLUSÃO PRA VALER": "06:00:00",
      "SEMENTES DA EDUCAÇÃO": "06:30:00",
      "PALALOOS": "07:00:00",
      "PLANETA PALAVRA": "07:10:00",
      "SONHOS E SAPATILHAS": "07:30:00",
      "SOL EM DÓ RÉ MI": "07:45:00",
      "IGARAPÉ MÁGICO": "08:00:00",
      "PASSADO DA HORA": "08:15:00",
      "ME LIGA NA LATA": "08:30:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA": "09:00:00",
      "SE LIGA NA EDUCAÇÃO": "09:30:00",
      "TRILHA DE LETRAS": "10:45:00",
      "HEROÍNAS NEGRAS BRASILEIRAS": "11:15:00",
      "GINT SERIADOS CANAL GOV": "11:25:00",
      "GAME DEV BRASIL": "11:30:00",
      "ESTÚDIO CIÊNCIA": "12:00:00",
      "DOC 100 + NOVOS INSTITUTOS FEDERAIS": "12:30:00",
      "SEM DÚVIDA NENHUMA": "12:45:00",
      "INCLUSÃO PRA VALER [2ª]": "13:00:00",
      "PALALOOS [2ª]": "13:30:00",
      "PLANETA PALAVRA [2ª]": "13:40:00",
      "SONHOS E SAPATILHAS [2ª]": "13:50:00",
      "SOL EM DÓ RÉ MI [2ª]": "14:05:00",
      "IGARAPÉ MÁGICO [2ª]": "14:15:00",
      "PASSADO DA HORA [2ª]": "14:30:00",
      "ME LIGA NA LATA [2ª]": "14:45:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]": "15:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]": "15:45:00",
      "GINT SERIADOS CANAL GOV [2ª]": "15:55:00",
      "SE LIGA NA EDUCAÇÃO [2ª]": "16:00:00",
      "TRILHA DE LETRAS [2ª]": "17:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]": "17:45:00",
      "GINT SERIADOS CANAL GOV [3ª]": "17:55:00",
      "GAME DEV BRASIL [2ª]": "18:00:00",
      "ESTÚDIO CIÊNCIA [2ª]": "18:30:00",
      "CAMINHOS DA REPORTAGEM": "19:00:00",
      "VIDA DE MERENDEIRA": "19:30:00",
      "INCLUSÃO PRA VALER [3ª]": "20:30:00",
      "FAROIS DO BRASIL": "21:00:00",
      "FORTES DO BRASIL": "21:30:00",
      "DOCUMENTARIOS TV SENADO GOV": "22:00:00",
      "VIDA DE MERENDEIRA [2ª]": "23:00:00"
    },
    "4": {
      "VIDA DE MERENDEIRA": "06:00:00",
      "PALALOOS": "07:00:00",
      "PLANETA PALAVRA": "07:10:00",
      "SONHOS E SAPATILHAS": "07:30:00",
      "SOL EM DÓ RÉ MI": "07:45:00",
      "IGARAPÉ MÁGICO": "08:00:00",
      "PASSADO DA HORA": "08:15:00",
      "ME LIGA NA LATA": "08:30:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA": "09:00:00",
      "SE LIGA NA EDUCAÇÃO": "09:30:00",
      "PORTUGUÊS DAQUI, PORTUGUÊS DE LÁ": "10:45:00",
      "HEROÍNAS NEGRAS BRASILEIRAS": "11:15:00",
      "GINT SERIADOS CANAL GOV": "11:25:00",
      "PROGRAMA HUMANIDADES": "11:30:00",
      "VIDA DE MERENDEIRA [2ª]": "12:30:00",
      "PALALOOS [2ª]": "13:30:00",
      "PLANETA PALAVRA [2ª]": "13:40:00",
      "SONHOS E SAPATILHAS [2ª]": "13:50:00",
      "SOL EM DÓ RÉ MI [2ª]": "14:05:00",
      "IGARAPÉ MÁGICO [2ª]": "14:15:00",
      "PASSADO DA HORA [2ª]": "14:30:00",
      "ME LIGA NA LATA [2ª]": "14:45:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]": "15:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]": "15:45:00",
      "GINT SERIADOS CANAL GOV [2ª]": "15:55:00",
      "SE LIGA NA EDUCAÇÃO [2ª]": "16:00:00",
      "PORTUGUÊS DAQUI, PORTUGUÊS DE LÁ [2ª]": "17:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]": "17:45:00",
      "GINT SERIADOS CANAL GOV [3ª]": "17:55:00",
      "PROGRAMA HUMANIDADES [2ª]": "18:00:00",
      "CAMINHOS DA REPORTAGEM": "19:00:00",
      "ESCOLA QUE PROTEGE": "19:30:00",
      "VIDA DE MERENDEIRA [3ª]": "20:30:00",
      "FAROIS DO BRASIL": "21:30:00",
      "CINCO MULHERES": "22:00:00",
      "SAL A GOSTO": "22:30:00",
      "ESCOLA QUE PROTEGE [2ª]": "23:00:00"
    },
    "5": {
      "ESCOLA QUE PROTEGE": "06:00:00",
      "PALALOOS": "07:00:00",
      "PLANETA PALAVRA": "07:10:00",
      "SONHOS E SAPATILHAS": "07:30:00",
      "SOL EM DÓ RÉ MI": "07:45:00",
      "IGARAPÉ MÁGICO": "08:00:00",
      "PASSADO DA HORA": "08:15:00",
      "ME LIGA NA LATA": "08:30:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA": "09:00:00",
      "SE LIGA NA EDUCAÇÃO": "09:30:00",
      "TRILHA DE LETRAS": "10:45:00",
      "HEROÍNAS NEGRAS BRASILEIRAS": "11:15:00",
      "GINT SERIADOS CANAL GOV": "11:25:00",
      "AÇÃO": "11:30:00",
      "UNIVERCIÊNCIA": "12:00:00",
      "ESCOLA QUE PROTEGE [2ª]": "12:30:00",
      "PALALOOS [2ª]": "13:30:00",
      "PLANETA PALAVRA [2ª]": "13:40:00",
      "SONHOS E SAPATILHAS [2ª]": "13:50:00",
      "SOL EM DÓ RÉ MI [2ª]": "14:05:00",
      "IGARAPÉ MÁGICO [2ª]": "14:15:00",
      "PASSADO DA HORA [2ª]": "14:30:00",
      "ME LIGA NA LATA [2ª]": "14:45:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]": "15:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]": "15:45:00",
      "GINT SERIADOS CANAL GOV [2ª]": "15:55:00",
      "SE LIGA NA EDUCAÇÃO [2ª]": "16:00:00",
      "TRILHA DE LETRAS [2ª]": "17:15:00",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]": "17:45:00",
      "GINT SERIADOS CANAL GOV [3ª]": "17:55:00",
      "AÇÃO [2ª]": "18:00:00",
      "UNIVERCIÊNCIA [2ª]": "18:30:00",
      "SEM DÚVIDA NENHUMA": "19:00:00",
      "PEQUENOS MESTRES": "19:15:00",
      "ESTAÇÕES": "19:30:00",
      "ESCOLA QUE PROTEGE [3ª]": "20:00:00",
      "MEU PEDAÇO DE BRASIL": "21:00:00",
      "NOSSOS BIOMAS": "21:30:00",
      "ENTRE LONGES": "22:00:00",
      "CINCO MULHERES": "22:30:00",
      "SEMENTES DA EDUCAÇÃO": "23:00:00",
      "SEM DÚVIDA NENHUMA [2ª]": "23:30:00",
      "PEQUENOS MESTRES [2ª]": "23:45:00"
    },
    "6": {
      "CONTA A VIRADA": "06:00:00",
      "OLHA ELAS!": "06:30:00",
      "GAME DEV BRASIL": "07:30:00",
      "PROGRAMA HUMANIDADES": "08:00:00",
      "AÇÃO": "09:00:00",
      "SEM DÚVIDA NENHUMA": "09:30:00",
      "PEQUENOS MESTRES": "09:45:00",
      "TRILHA DE LETRAS": "10:00:00",
      "ESTÚDIO CIÊNCIA": "10:30:00",
      "ESCOLA QUE PROTEGE": "11:00:00",
      "VIDA DE MERENDEIRA": "12:00:00",
      "ADOLESCENTES E O MUNDO DIGITAL": "13:00:00",
      "PALALOOS": "13:30:00",
      "PLANETA PALAVRA": "13:40:00",
      "SOL EM DÓ RÉ MI": "14:10:00",
      "PASSADO DA HORA": "14:50:00",
      "ME LIGA NA LATA": "15:30:00",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA": "16:30:00",
      "PARQUES DO BRASIL": "17:00:00",
      "FORTES DO BRASIL": "17:30:00",
      "FAROIS DO BRASIL": "18:00:00",
      "NOSSOS BIOMAS": "18:30:00",
      "MEU PEDAÇO DE BRASIL": "19:00:00",
      "SAL A GOSTO": "19:30:00",
      "CINCO MULHERES": "20:00:00",
      "TEÓPHILO OTTONI": "20:30:00",
      "DOCUMENTARIOS TV SENADO GOV": "21:00:00",
      "CAMINHOS DA REPORTAGEM": "22:00:00",
      "ESCOLA QUE PROTEGE [2ª]": "23:00:00"
    },
    "0": {
      "MUTATIS MUTANDIS": "06:00:00",
      "TRILHA DE LETRAS": "06:30:00",
      "ENTRELINHAS": "07:00:00",
      "ESTÚDIO CIÊNCIA": "07:30:00",
      "TRILHA DE LETRAS [2ª]": "08:00:00",
      "PORTUGUÊS DAQUI, PORTUGUÊS DE LÁ": "08:30:00",
      "UNIVERCIÊNCIA": "09:00:00",
      "TRILHA DE LETRAS [3ª]": "09:30:00",
      "SONHOS E SAPATILHAS": "10:00:00",
      "ME LIGA NA LATA": "10:50:00",
      "HEROÍNAS NEGRAS BRASILEIRAS": "12:20:00",
      "CONTA A VIRADA": "12:30:00",
      "OLHA ELAS!": "13:00:00",
      "CAMINHOS DA REPORTAGEM": "14:00:00",
      "SEM DÚVIDA NENHUMA": "14:30:00",
      "PEQUENOS MESTRES": "14:45:00",
      "DOCUMENTARIOS TV SENADO GOV": "15:00:00",
      "MUTATIS MUTANDIS [2ª]": "16:00:00",
      "SAL A GOSTO": "16:30:00",
      "TEÓPHILO OTTONI": "17:00:00",
      "ENTRE LONGES": "17:30:00",
      "CINCO MULHERES": "18:00:00",
      "ESTAÇÕES": "18:30:00",
      "SEMENTES DA EDUCAÇÃO": "19:00:00",
      "ESCOLA QUE PROTEGE": "19:30:00",
      "ADOLESCENTES E O MUNDO DIGITAL": "20:30:00",
      "INCLUSÃO PRA VALER": "21:00:00",
      "VIDA DE MERENDEIRA": "21:30:00",
      "FORTES DO BRASIL": "22:30:00",
      "FAROIS DO BRASIL": "23:00:00",
      "PARQUES DO BRASIL": "23:30:00"
    }
  },
  "gradeOrderByDay": {
    "1": [
      "ESTAÇÕES",
      "SEMENTES DA EDUCAÇÃO",
      "PALALOOS",
      "PLANETA PALAVRA",
      "SONHOS E SAPATILHAS",
      "SOL EM DÓ RÉ MI",
      "IGARAPÉ MÁGICO",
      "PASSADO DA HORA",
      "ME LIGA NA LATA",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA",
      "SE LIGA NA EDUCAÇÃO",
      "TRILHA DE LETRAS",
      "HEROÍNAS NEGRAS BRASILEIRAS",
      "GINT SERIADOS CANAL GOV",
      "CONTA A VIRADA",
      "MUTATIS MUTANDIS",
      "SEMENTES DA EDUCAÇÃO [2ª]",
      "SEM DÚVIDA NENHUMA",
      "DOC 100 + NOVOS INSTITUTOS FEDERAIS",
      "PALALOOS [2ª]",
      "PLANETA PALAVRA [2ª]",
      "SONHOS E SAPATILHAS [2ª]",
      "SOL EM DÓ RÉ MI [2ª]",
      "IGARAPÉ MÁGICO [2ª]",
      "PASSADO DA HORA [2ª]",
      "ME LIGA NA LATA [2ª]",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]",
      "GINT SERIADOS CANAL GOV [2ª]",
      "SE LIGA NA EDUCAÇÃO [2ª]",
      "TRILHA DE LETRAS [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]",
      "GINT SERIADOS CANAL GOV [3ª]",
      "CONTA A VIRADA [2ª]",
      "MUTATIS MUTANDIS [2ª]",
      "CAMINHOS DA REPORTAGEM",
      "ADOLESCENTES E O MUNDO DIGITAL",
      "SEMENTES DA EDUCAÇÃO [3ª]",
      "SEM DÚVIDA NENHUMA [2ª]",
      "DOC 100 + NOVOS INSTITUTOS FEDERAIS [2ª]",
      "PARQUES DO BRASIL",
      "MEU PEDAÇO DE BRASIL",
      "TEÓPHILO OTTONI",
      "ENTRE LONGES",
      "SEMENTES DA EDUCAÇÃO [4ª]",
      "ADOLESCENTES E O MUNDO DIGITAL [2ª]"
    ],
    "2": [
      "ADOLESCENTES E O MUNDO DIGITAL",
      "SEMENTES DA EDUCAÇÃO",
      "PALALOOS",
      "PLANETA PALAVRA",
      "SONHOS E SAPATILHAS",
      "SOL EM DÓ RÉ MI",
      "IGARAPÉ MÁGICO",
      "PASSADO DA HORA",
      "ME LIGA NA LATA",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA",
      "SE LIGA NA EDUCAÇÃO",
      "ENTRELINHAS",
      "HEROÍNAS NEGRAS BRASILEIRAS",
      "GINT SERIADOS CANAL GOV",
      "OLHA ELAS!",
      "SEMENTES DA EDUCAÇÃO [2ª]",
      "ADOLESCENTES E O MUNDO DIGITAL [2ª]",
      "PALALOOS [2ª]",
      "PLANETA PALAVRA [2ª]",
      "SONHOS E SAPATILHAS [2ª]",
      "SOL EM DÓ RÉ MI [2ª]",
      "IGARAPÉ MÁGICO [2ª]",
      "PASSADO DA HORA [2ª]",
      "ME LIGA NA LATA [2ª]",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]",
      "GINT SERIADOS CANAL GOV [2ª]",
      "SE LIGA NA EDUCAÇÃO [2ª]",
      "ENTRELINHAS [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]",
      "GINT SERIADOS CANAL GOV [3ª]",
      "OLHA ELAS! [2ª]",
      "CAMINHOS DA REPORTAGEM",
      "INCLUSÃO PRA VALER",
      "SEMENTES DA EDUCAÇÃO [3ª]",
      "ADOLESCENTES E O MUNDO DIGITAL [3ª]",
      "FORTES DO BRASIL",
      "PARQUES DO BRASIL",
      "SAL A GOSTO",
      "TEÓPHILO OTTONI",
      "SEMENTES DA EDUCAÇÃO [4ª]",
      "INCLUSÃO PRA VALER [2ª]"
    ],
    "3": [
      "INCLUSÃO PRA VALER",
      "SEMENTES DA EDUCAÇÃO",
      "PALALOOS",
      "PLANETA PALAVRA",
      "SONHOS E SAPATILHAS",
      "SOL EM DÓ RÉ MI",
      "IGARAPÉ MÁGICO",
      "PASSADO DA HORA",
      "ME LIGA NA LATA",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA",
      "SE LIGA NA EDUCAÇÃO",
      "TRILHA DE LETRAS",
      "HEROÍNAS NEGRAS BRASILEIRAS",
      "GINT SERIADOS CANAL GOV",
      "GAME DEV BRASIL",
      "ESTÚDIO CIÊNCIA",
      "DOC 100 + NOVOS INSTITUTOS FEDERAIS",
      "SEM DÚVIDA NENHUMA",
      "INCLUSÃO PRA VALER [2ª]",
      "PALALOOS [2ª]",
      "PLANETA PALAVRA [2ª]",
      "SONHOS E SAPATILHAS [2ª]",
      "SOL EM DÓ RÉ MI [2ª]",
      "IGARAPÉ MÁGICO [2ª]",
      "PASSADO DA HORA [2ª]",
      "ME LIGA NA LATA [2ª]",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]",
      "GINT SERIADOS CANAL GOV [2ª]",
      "SE LIGA NA EDUCAÇÃO [2ª]",
      "TRILHA DE LETRAS [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]",
      "GINT SERIADOS CANAL GOV [3ª]",
      "GAME DEV BRASIL [2ª]",
      "ESTÚDIO CIÊNCIA [2ª]",
      "CAMINHOS DA REPORTAGEM",
      "VIDA DE MERENDEIRA",
      "INCLUSÃO PRA VALER [3ª]",
      "FAROIS DO BRASIL",
      "FORTES DO BRASIL",
      "DOCUMENTARIOS TV SENADO GOV",
      "VIDA DE MERENDEIRA [2ª]"
    ],
    "4": [
      "VIDA DE MERENDEIRA",
      "PALALOOS",
      "PLANETA PALAVRA",
      "SONHOS E SAPATILHAS",
      "SOL EM DÓ RÉ MI",
      "IGARAPÉ MÁGICO",
      "PASSADO DA HORA",
      "ME LIGA NA LATA",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA",
      "SE LIGA NA EDUCAÇÃO",
      "PORTUGUÊS DAQUI, PORTUGUÊS DE LÁ",
      "HEROÍNAS NEGRAS BRASILEIRAS",
      "GINT SERIADOS CANAL GOV",
      "PROGRAMA HUMANIDADES",
      "VIDA DE MERENDEIRA [2ª]",
      "PALALOOS [2ª]",
      "PLANETA PALAVRA [2ª]",
      "SONHOS E SAPATILHAS [2ª]",
      "SOL EM DÓ RÉ MI [2ª]",
      "IGARAPÉ MÁGICO [2ª]",
      "PASSADO DA HORA [2ª]",
      "ME LIGA NA LATA [2ª]",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]",
      "GINT SERIADOS CANAL GOV [2ª]",
      "SE LIGA NA EDUCAÇÃO [2ª]",
      "PORTUGUÊS DAQUI, PORTUGUÊS DE LÁ [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]",
      "GINT SERIADOS CANAL GOV [3ª]",
      "PROGRAMA HUMANIDADES [2ª]",
      "CAMINHOS DA REPORTAGEM",
      "ESCOLA QUE PROTEGE",
      "VIDA DE MERENDEIRA [3ª]",
      "FAROIS DO BRASIL",
      "CINCO MULHERES",
      "SAL A GOSTO",
      "ESCOLA QUE PROTEGE [2ª]"
    ],
    "5": [
      "ESCOLA QUE PROTEGE",
      "PALALOOS",
      "PLANETA PALAVRA",
      "SONHOS E SAPATILHAS",
      "SOL EM DÓ RÉ MI",
      "IGARAPÉ MÁGICO",
      "PASSADO DA HORA",
      "ME LIGA NA LATA",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA",
      "SE LIGA NA EDUCAÇÃO",
      "TRILHA DE LETRAS",
      "HEROÍNAS NEGRAS BRASILEIRAS",
      "GINT SERIADOS CANAL GOV",
      "AÇÃO",
      "UNIVERCIÊNCIA",
      "ESCOLA QUE PROTEGE [2ª]",
      "PALALOOS [2ª]",
      "PLANETA PALAVRA [2ª]",
      "SONHOS E SAPATILHAS [2ª]",
      "SOL EM DÓ RÉ MI [2ª]",
      "IGARAPÉ MÁGICO [2ª]",
      "PASSADO DA HORA [2ª]",
      "ME LIGA NA LATA [2ª]",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [2ª]",
      "GINT SERIADOS CANAL GOV [2ª]",
      "SE LIGA NA EDUCAÇÃO [2ª]",
      "TRILHA DE LETRAS [2ª]",
      "HEROÍNAS NEGRAS BRASILEIRAS [3ª]",
      "GINT SERIADOS CANAL GOV [3ª]",
      "AÇÃO [2ª]",
      "UNIVERCIÊNCIA [2ª]",
      "SEM DÚVIDA NENHUMA",
      "PEQUENOS MESTRES",
      "ESTAÇÕES",
      "ESCOLA QUE PROTEGE [3ª]",
      "MEU PEDAÇO DE BRASIL",
      "NOSSOS BIOMAS",
      "ENTRE LONGES",
      "CINCO MULHERES",
      "SEMENTES DA EDUCAÇÃO",
      "SEM DÚVIDA NENHUMA [2ª]",
      "PEQUENOS MESTRES [2ª]"
    ],
    "6": [
      "CONTA A VIRADA",
      "OLHA ELAS!",
      "GAME DEV BRASIL",
      "PROGRAMA HUMANIDADES",
      "AÇÃO",
      "SEM DÚVIDA NENHUMA",
      "PEQUENOS MESTRES",
      "TRILHA DE LETRAS",
      "ESTÚDIO CIÊNCIA",
      "ESCOLA QUE PROTEGE",
      "VIDA DE MERENDEIRA",
      "ADOLESCENTES E O MUNDO DIGITAL",
      "PALALOOS",
      "PLANETA PALAVRA",
      "SOL EM DÓ RÉ MI",
      "PASSADO DA HORA",
      "ME LIGA NA LATA",
      "MANUAL DE SOBREVIVÊNCIA DA LITERATURA BRASILEIRA",
      "PARQUES DO BRASIL",
      "FORTES DO BRASIL",
      "FAROIS DO BRASIL",
      "NOSSOS BIOMAS",
      "MEU PEDAÇO DE BRASIL",
      "SAL A GOSTO",
      "CINCO MULHERES",
      "TEÓPHILO OTTONI",
      "DOCUMENTARIOS TV SENADO GOV",
      "CAMINHOS DA REPORTAGEM",
      "ESCOLA QUE PROTEGE [2ª]"
    ],
    "0": [
      "MUTATIS MUTANDIS",
      "TRILHA DE LETRAS",
      "ENTRELINHAS",
      "ESTÚDIO CIÊNCIA",
      "TRILHA DE LETRAS [2ª]",
      "PORTUGUÊS DAQUI, PORTUGUÊS DE LÁ",
      "UNIVERCIÊNCIA",
      "TRILHA DE LETRAS [3ª]",
      "SONHOS E SAPATILHAS",
      "ME LIGA NA LATA",
      "HEROÍNAS NEGRAS BRASILEIRAS",
      "CONTA A VIRADA",
      "OLHA ELAS!",
      "CAMINHOS DA REPORTAGEM",
      "SEM DÚVIDA NENHUMA",
      "PEQUENOS MESTRES",
      "DOCUMENTARIOS TV SENADO GOV",
      "MUTATIS MUTANDIS [2ª]",
      "SAL A GOSTO",
      "TEÓPHILO OTTONI",
      "ENTRE LONGES",
      "CINCO MULHERES",
      "ESTAÇÕES",
      "SEMENTES DA EDUCAÇÃO",
      "ESCOLA QUE PROTEGE",
      "ADOLESCENTES E O MUNDO DIGITAL",
      "INCLUSÃO PRA VALER",
      "VIDA DE MERENDEIRA",
      "FORTES DO BRASIL",
      "FAROIS DO BRASIL",
      "PARQUES DO BRASIL"
    ]
  }
};

// [MOD canal-gov] Alias de compatibilidade: código legado que ainda use o
// nome antigo `GRADE_BASE` continua funcionando, apontando para a grade da
// Educação (comportamento idêntico ao de antes desta entrega).
const GRADE_BASE = GRADE_BASE_EDUCACAO;

/**
 * [MOD canal-gov] GRADE_BASE_GOV — grade de referência do Canal Gov.
 * Começa VAZIA (nenhum horário-base cadastrado ainda) porque não recebi
 * uma planilha de programação do Gov nesta entrega — só o mapeamento de
 * types. Estrutura idêntica à de GRADE_BASE_EDUCACAO, para que
 * loadGrade()/loadGradeOrder() (app.js) funcionem sem alterações extras
 * assim que a grade real do Gov for cadastrada (pelo modal de importação
 * de Grade Semanal, ou editando este arquivo diretamente).
 */
const GRADE_BASE_GOV = {
  "gradeByDay": { "0": {}, "1": {}, "2": {}, "3": {}, "4": {}, "5": {}, "6": {} },
  "gradeOrderByDay": { "0": [], "1": [], "2": [], "3": [], "4": [], "5": [], "6": [] }
};

/**
 * [MOD canal-gov] Retorna a GRADE_BASE correta para a emissora ATUALMENTE
 * selecionada — essencial para regra_1: sem isso, o Canal Gov cairia no
 * fallback da grade do Canal Educação (GRADE_BASE_EDUCACAO) sempre que
 * ainda não tivesse uma grade customizada salva.
 * Depende de `window.Emissora` (definido em emissora.js); se ainda não
 * estiver carregado, assume Educação (comportamento anterior, seguro).
 */
function gradeBaseAtual() {
  const emissora = (typeof window !== 'undefined' && window.Emissora && window.Emissora.get)
    ? window.Emissora.get()
    : 'educacao';
  return emissora === 'gov' ? GRADE_BASE_GOV : GRADE_BASE_EDUCACAO;
}

/**
 * [MOD canal-gov] Mesma lógica de chaveStorage() do app.js, duplicada aqui
 * porque este arquivo é carregado ANTES de app.js (ver DOCUMENTACAO.md
 * §2, ordem de carga dos scripts). Se app.js já tiver definido
 * `chaveStorage` (quando esta função for efetivamente CHAMADA, não quando
 * for definida), usa a versão dele para não haver duas fontes de verdade.
 */
function _chaveStorageGrade(nomeBase) {
  if (typeof chaveStorage === 'function') return chaveStorage(nomeBase);
  const emissora = (typeof window !== 'undefined' && window.Emissora && window.Emissora.get)
    ? window.Emissora.get()
    : 'educacao';
  return `${nomeBase}__${emissora}`;
}

// Load grade for a day-of-week, falling back to GRADE_BASE if not yet customized
/** Carrega a grade para o dia dow priorizando customizações do usuário no localStorage. Se não houver customização, usa os dados base da emissora atual (GRADE_BASE_EDUCACAO ou GRADE_BASE_GOV — ver gradeBaseAtual()). */
function loadGradeWithBase(dow) {
  // [MOD canal-gov] chave de storage isolada por emissora (regra_1).
  const saved = JSON.parse(localStorage.getItem(_chaveStorageGrade('roteiroApp')) || '{}');
  const customGrade = (saved.gradeByDay || {})[dow];
  // If user has a saved grade for this day, use it; otherwise fall back to GRADE_BASE da emissora atual
  if (customGrade && Object.keys(customGrade).length > 0) return customGrade;
  return gradeBaseAtual().gradeByDay[String(dow)] || {};
}

/** Carrega a ordem dos programas para o dia dow. Prioridade: localStorage → grade base da emissora atual. */
function loadGradeOrderWithBase(dow) {
  // [MOD canal-gov] chave de storage isolada por emissora (regra_1).
  const saved = JSON.parse(localStorage.getItem(_chaveStorageGrade('roteiroApp')) || '{}');
  const customOrder = (saved.gradeOrderByDay || {})[dow];
  if (customOrder && customOrder.length > 0) return customOrder;
  return gradeBaseAtual().gradeOrderByDay[String(dow)] || [];
}
